### ISSUE TITLE
add github workflow and dependabot

### ISSUE THREAD

**Issue by its-me-debk007** [utkarsh006/Notes-app-compose#4]
Can implement GitHub Actions workflow to check if the code pushed to the branch doesn't contain any compilation errors. 
Also, can add dependabot to automate the updation of dependencies in the project.

**Comment by utkarsh006** [comment]
@its-me-debk007 Sure Go Ahead ❤️

**Comment by its-me-debk007** [comment]
I see there's a PR already about adding workflow without an issue.
I guess I'll add the dependabot
